// generated by xgen -- DO NOT EDIT
package dict

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type DTOs []DTO

type DTO struct {
	dto.Sys
	Genre   string `json:"genre"`
	Descr   string `json:"descr"`
	Mkey    string `json:"mkey"`
	Mval    string `json:"mval"`
	Filters string `json:"filters"`
	Ordinal string `json:"ordinal"`
}
