// generated by xgen -- DO NOT EDIT
package role

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type PostDTOs []PostDTO

type PostDTO struct {
	dto.Sys
	RoleId string `json:"roleId"`
	PostId string `json:"postId"`
}
