// generated by xgen -- DO NOT EDIT
package user

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type RoleDTOs []RoleDTO

type RoleDTO struct {
	dto.Sys
	UserId string `json:"userId"`
	RoleId string `json:"roleId"`
}
