// generated by xgen -- DO NOT EDIT
package user

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var roleCtl = &RoleController{
	ClientController: controller.ClientController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "user.role",
			Title:   "USER ROLE",
		},
		DTO: func() interface{} {
			return &RoleDTO{}
		},
		DTOs: func() interface{} {
			return &RoleDTOs{}
		},
	},
}

type RoleController struct {
	controller.ClientController
}
