// generated by xgen -- DO NOT EDIT
package user

import (
	"bytes"
	"fmt"
	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/schema"
	"gopkg.in/goyy/goyy.v0/util/strings"
)

var (
	ROLE_ENTITY           = schema.TABLE("")
	ROLE_ENTITY_ID        = ROLE_ENTITY.PRIMARY("id")
	ROLE_ENTITY_MEMO      = ROLE_ENTITY.COLUMN("memo")
	ROLE_ENTITY_CREATES   = ROLE_ENTITY.COLUMN("creates")
	ROLE_ENTITY_CREATER   = ROLE_ENTITY.CREATER("creater")
	ROLE_ENTITY_CREATED   = ROLE_ENTITY.CREATED("created")
	ROLE_ENTITY_MODIFIER  = ROLE_ENTITY.MODIFIER("modifier")
	ROLE_ENTITY_MODIFIED  = ROLE_ENTITY.MODIFIED("modified")
	ROLE_ENTITY_VERSION   = ROLE_ENTITY.VERSION("version")
	ROLE_ENTITY_DELETION  = ROLE_ENTITY.DELETION("deletion")
	ROLE_ENTITY_ARTIFICAL = ROLE_ENTITY.COLUMN("artifical")
	ROLE_ENTITY_HISTORY   = ROLE_ENTITY.COLUMN("history")
)

func NewRoleEntity() *RoleEntity {
	e := &RoleEntity{}
	e.init()
	return e
}

func (me *RoleEntity) init() {
	me.table = ROLE_ENTITY

	if t, ok := me.Sys.Type("id"); ok {
		t.SetColumn(ROLE_ENTITY_ID)
	}
	if t, ok := me.Sys.Type("memo"); ok {
		t.SetColumn(ROLE_ENTITY_MEMO)
	}
	if t, ok := me.Sys.Type("creates"); ok {
		t.SetColumn(ROLE_ENTITY_CREATES)
	}
	if t, ok := me.Sys.Type("creater"); ok {
		t.SetColumn(ROLE_ENTITY_CREATER)
	}
	if t, ok := me.Sys.Type("created"); ok {
		t.SetColumn(ROLE_ENTITY_CREATED)
	}
	if t, ok := me.Sys.Type("modifier"); ok {
		t.SetColumn(ROLE_ENTITY_MODIFIER)
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetColumn(ROLE_ENTITY_MODIFIED)
	}
	if t, ok := me.Sys.Type("version"); ok {
		t.SetColumn(ROLE_ENTITY_VERSION)
	}
	if t, ok := me.Sys.Type("deletion"); ok {
		t.SetColumn(ROLE_ENTITY_DELETION)
	}
	if t, ok := me.Sys.Type("artifical"); ok {
		t.SetColumn(ROLE_ENTITY_ARTIFICAL)
	}
	if t, ok := me.Sys.Type("history"); ok {
		t.SetColumn(ROLE_ENTITY_HISTORY)
	}

	if t, ok := me.Sys.Type("created"); ok {
		t.SetDefault("-62135596800")
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetDefault("-62135596800")
	}

	columns := []string{"id", "memo", "creates", "creater", "created", "modifier", "modified",
		"version", "deletion", "artifical", "history"}
	for _, c := range columns {
		if t, ok := me.Sys.Type(c); ok {
			t.SetField(entity.DefaultField())
		}
	}
}

func (me RoleEntity) New() entity.Interface {
	return NewRoleEntity()
}

func (me *RoleEntity) Get(column string) interface{} {
	switch column {
	}
	return me.Sys.Get(column)
}

func (me *RoleEntity) GetPtr(column string) interface{} {
	switch column {
	}
	return me.Sys.GetPtr(column)
}

func (me *RoleEntity) Table() schema.Table {
	return me.table
}

func (me *RoleEntity) Type(column string) (entity.Type, bool) {
	switch column {
	}
	return me.Sys.Type(column)
}

func (me *RoleEntity) Column(field string) (schema.Column, bool) {
	switch strings.ToLowerFirst(field) {
	}
	return me.Sys.Column(field)
}

func (me *RoleEntity) Columns() []schema.Column {
	return []schema.Column{
		ROLE_ENTITY_ID,
		ROLE_ENTITY_MEMO,
		ROLE_ENTITY_CREATES,
		ROLE_ENTITY_CREATER,
		ROLE_ENTITY_CREATED,
		ROLE_ENTITY_MODIFIER,
		ROLE_ENTITY_MODIFIED,
		ROLE_ENTITY_VERSION,
		ROLE_ENTITY_DELETION,
		ROLE_ENTITY_ARTIFICAL,
		ROLE_ENTITY_HISTORY,
	}
}

func (me *RoleEntity) Names() []string {
	return []string{
		"id",
		"memo",
		"creates",
		"creater",
		"created",
		"modifier",
		"modified",
		"version",
		"deletion",
		"artifical",
		"history",
	}
}

func (me *RoleEntity) Value() *RoleEntity {
	return me
}

func (me *RoleEntity) SetString(field, value string) error {
	switch strings.ToLowerFirst(field) {
	}
	return me.Sys.SetString(field, value)
}

func (me *RoleEntity) Validate() error {
	return nil
}

func (me *RoleEntity) JSON() string {
	var b bytes.Buffer
	b.WriteString("{")
	b.WriteString(fmt.Sprintf(`"id":%q`, me.Sys.Pk.Id()))
	b.WriteString(fmt.Sprintf(`,"memo":%q`, me.Sys.Memo()))
	b.WriteString(fmt.Sprintf(`,"creates":%q`, me.Sys.Creates()))
	b.WriteString(fmt.Sprintf(`,"creater":%q`, me.Sys.Creater()))
	b.WriteString(fmt.Sprintf(`,"created":%d`, me.Sys.Created()))
	b.WriteString(fmt.Sprintf(`,"modifier":%q`, me.Sys.Modifier()))
	b.WriteString(fmt.Sprintf(`,"modified":%d`, me.Sys.Modified()))
	b.WriteString(fmt.Sprintf(`,"version":%d`, me.Sys.Version()))
	b.WriteString(fmt.Sprintf(`,"deletion":%d`, me.Sys.Deletion()))
	b.WriteString(fmt.Sprintf(`,"artifical":%d`, me.Sys.Artifical()))
	b.WriteString(fmt.Sprintf(`,"history":%d`, me.Sys.History()))
	b.WriteString("}")
	return b.String()
}
