// generated by xgen -- DO NOT EDIT
package post

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var menuCtl = &MenuController{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "post.menu",
			Title:   "POST MENU",
		},
		Mgr: MenuMgr,
	},
}

type MenuController struct {
	controller.JSONController
}
