// generated by xgen -- DO NOT EDIT
package order

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var ctl = &Controller{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "example",
			Module:  "order",
			Title:   "订单信息",
		},
		Mgr: Mgr,
	},
}

type Controller struct {
	controller.JSONController
}
