// generated by xgen -- DO NOT EDIT
package menu

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type DTOs []DTO

type DTO struct {
	dto.Tree
	Href       string `json:"href"`
	Target     string `json:"target"`
	Icon       string `json:"icon"`
	Hidden     bool   `json:"hidden"`
	Permission string `json:"permission"`
}
