// generated by xgen -- DO NOT EDIT
package role

import (
	"bytes"

	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/schema"
	"gopkg.in/goyy/goyy.v0/util/jsons"
	"gopkg.in/goyy/goyy.v0/util/strings"
)

var (
	POST_ENTITY           = schema.TABLE("sys_role_post", "ROLE POST")
	POST_ENTITY_ID        = POST_ENTITY.PRIMARY("id", "ID")
	POST_ENTITY_MEMO      = POST_ENTITY.COLUMN("memo", "MEMO")
	POST_ENTITY_CREATES   = POST_ENTITY.COLUMN("creates", "CREATES")
	POST_ENTITY_CREATER   = POST_ENTITY.CREATER("creater", "CREATER")
	POST_ENTITY_CREATED   = POST_ENTITY.CREATED("created", "CREATED")
	POST_ENTITY_MODIFIER  = POST_ENTITY.MODIFIER("modifier", "MODIFIER")
	POST_ENTITY_MODIFIED  = POST_ENTITY.MODIFIED("modified", "MODIFIED")
	POST_ENTITY_VERSION   = POST_ENTITY.VERSION("version", "VERSION")
	POST_ENTITY_DELETION  = POST_ENTITY.DELETION("deletion", "DELETION")
	POST_ENTITY_ARTIFICAL = POST_ENTITY.COLUMN("artifical", "ARTIFICAL")
	POST_ENTITY_HISTORY   = POST_ENTITY.COLUMN("history", "HISTORY")
	POST_ENTITY_ROLE_ID   = POST_ENTITY.COLUMN("role_id", "ROLE_ID")
	POST_ENTITY_POST_ID   = POST_ENTITY.COLUMN("post_id", "POST_ID")
)

func NewPostEntity() *PostEntity {
	e := &PostEntity{}
	e.init()
	return e
}

func (me *PostEntity) RoleId() string {
	return me.roleId.Value()
}

func (me *PostEntity) SetRoleId(v string) {
	me.roleId.SetValue(v)
}

func (me *PostEntity) PostId() string {
	return me.postId.Value()
}

func (me *PostEntity) SetPostId(v string) {
	me.postId.SetValue(v)
}

func (me *PostEntity) init() {
	me.table = POST_ENTITY
	me.initSetDict()
	me.initSetColumn()
	me.initSetDefault()
	me.initSetField()
	me.initSetExcel()
	me.initSetJson()
	me.initSetXml()
}

func (me *PostEntity) initSetDict() {
}

func (me *PostEntity) initSetColumn() {
	if t, ok := me.Sys.Type("id"); ok {
		t.SetColumn(POST_ENTITY_ID)
	}
	if t, ok := me.Sys.Type("memo"); ok {
		t.SetColumn(POST_ENTITY_MEMO)
	}
	if t, ok := me.Sys.Type("creates"); ok {
		t.SetColumn(POST_ENTITY_CREATES)
	}
	if t, ok := me.Sys.Type("creater"); ok {
		t.SetColumn(POST_ENTITY_CREATER)
	}
	if t, ok := me.Sys.Type("created"); ok {
		t.SetColumn(POST_ENTITY_CREATED)
	}
	if t, ok := me.Sys.Type("modifier"); ok {
		t.SetColumn(POST_ENTITY_MODIFIER)
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetColumn(POST_ENTITY_MODIFIED)
	}
	if t, ok := me.Sys.Type("version"); ok {
		t.SetColumn(POST_ENTITY_VERSION)
	}
	if t, ok := me.Sys.Type("deletion"); ok {
		t.SetColumn(POST_ENTITY_DELETION)
	}
	if t, ok := me.Sys.Type("artifical"); ok {
		t.SetColumn(POST_ENTITY_ARTIFICAL)
	}
	if t, ok := me.Sys.Type("history"); ok {
		t.SetColumn(POST_ENTITY_HISTORY)
	}
	me.roleId.SetColumn(POST_ENTITY_ROLE_ID)
	me.postId.SetColumn(POST_ENTITY_POST_ID)
}

func (me *PostEntity) initSetDefault() {
	if t, ok := me.Sys.Type("created"); ok {
		t.SetDefault("-62135596800")
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetDefault("-62135596800")
	}
}

func (me *PostEntity) initSetField() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.SetField(entity.DefaultField())
		}
	}
	me.roleId.SetField(entity.DefaultField())
	me.postId.SetField(entity.DefaultField())
}

func (me *PostEntity) initSetExcel() {
}

func (me *PostEntity) initSetJson() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.Field().SetJson(entity.NewJsonBy(c))
		}
	}
	me.roleId.Field().SetJson(entity.NewJsonBy("roleId"))
	me.postId.Field().SetJson(entity.NewJsonBy("postId"))
}

func (me *PostEntity) initSetXml() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.Field().SetXml(entity.NewXmlBy(c))
		}
	}
	me.roleId.Field().SetXml(entity.NewXmlBy("roleId"))
	me.postId.Field().SetXml(entity.NewXmlBy("postId"))
}

func (me PostEntity) New() entity.Interface {
	return NewPostEntity()
}

func (me *PostEntity) Get(column string) interface{} {
	switch column {
	case POST_ENTITY_ROLE_ID.Name():
		return me.roleId.Value()
	case POST_ENTITY_POST_ID.Name():
		return me.postId.Value()
	}
	return me.Sys.Get(column)
}

func (me *PostEntity) GetPtr(column string) interface{} {
	switch column {
	case POST_ENTITY_ROLE_ID.Name():
		return me.roleId.ValuePtr()
	case POST_ENTITY_POST_ID.Name():
		return me.postId.ValuePtr()
	}
	return me.Sys.GetPtr(column)
}

func (me *PostEntity) GetString(field string) string {
	switch strings.ToLowerFirst(field) {
	case "roleId":
		return me.roleId.String()
	case "postId":
		return me.postId.String()
	}
	return me.Sys.GetString(field)
}

func (me *PostEntity) SetString(field, value string) error {
	switch strings.ToLowerFirst(field) {
	case "roleId":
		return me.roleId.SetString(value)
	case "postId":
		return me.postId.SetString(value)
	}
	return me.Sys.SetString(field, value)
}

func (me *PostEntity) Table() schema.Table {
	return me.table
}

func (me *PostEntity) Type(column string) (entity.Type, bool) {
	switch column {
	case POST_ENTITY_ROLE_ID.Name():
		return &me.roleId, true
	case POST_ENTITY_POST_ID.Name():
		return &me.postId, true
	}
	return me.Sys.Type(column)
}

func (me *PostEntity) Column(field string) (schema.Column, bool) {
	switch strings.ToLowerFirst(field) {
	case "roleId":
		return POST_ENTITY_ROLE_ID, true
	case "postId":
		return POST_ENTITY_POST_ID, true
	}
	return me.Sys.Column(field)
}

func (me *PostEntity) Columns() []schema.Column {
	return []schema.Column{
		POST_ENTITY_ID,
		POST_ENTITY_MEMO,
		POST_ENTITY_CREATES,
		POST_ENTITY_CREATER,
		POST_ENTITY_CREATED,
		POST_ENTITY_MODIFIER,
		POST_ENTITY_MODIFIED,
		POST_ENTITY_VERSION,
		POST_ENTITY_DELETION,
		POST_ENTITY_ARTIFICAL,
		POST_ENTITY_HISTORY,
		POST_ENTITY_ROLE_ID,
		POST_ENTITY_POST_ID,
	}
}

func (me *PostEntity) Names() []string {
	return []string{
		"id",
		"memo",
		"creates",
		"creater",
		"created",
		"modifier",
		"modified",
		"version",
		"deletion",
		"artifical",
		"history",
		"roleId",
		"postId",
	}
}

func (me *PostEntity) Value() *PostEntity {
	return me
}

func (me *PostEntity) Validate() error {
	return nil
}

func (me *PostEntity) JSON() string {
	var b bytes.Buffer
	b.WriteString("{")
	b.WriteString(`"id":"` + jsons.Format(me.GetString("id")) + `"`)
	b.WriteString(`,"memo":"` + jsons.Format(me.GetString("memo")) + `"`)
	b.WriteString(`,"creates":"` + jsons.Format(me.GetString("creates")) + `"`)
	b.WriteString(`,"creater":"` + jsons.Format(me.GetString("creater")) + `"`)
	b.WriteString(`,"created":` + me.GetString("created"))
	b.WriteString(`,"modifier":"` + jsons.Format(me.GetString("modifier")) + `"`)
	b.WriteString(`,"modified":` + me.GetString("modified"))
	b.WriteString(`,"version":` + me.GetString("version"))
	b.WriteString(`,"deletion":` + me.GetString("deletion"))
	b.WriteString(`,"artifical":` + me.GetString("artifical"))
	b.WriteString(`,"history":` + me.GetString("history"))
	b.WriteString(`,"roleId":"` + jsons.Format(me.GetString("roleId")) + `"`)
	b.WriteString(`,"postId":"` + jsons.Format(me.GetString("postId")) + `"`)
	b.WriteString("}")
	return b.String()
}

func (me *PostEntity) ExcelColumns() []string {
	return nil
}
