// generated by xgen -- DO NOT EDIT
package role

import (
	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/service"
)

var PostMgr = &PostManager{
	Manager: service.Manager{
		Entity: func() entity.Interface {
			return NewPostEntity()
		},
		Entities: func() entity.Interfaces {
			return NewPostEntities(10)
		},
	},
}

type PostManager struct {
	service.Manager
}
