// generated by xgen -- DO NOT EDIT
package role

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var postCtl = &PostController{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "role.post",
			Title:   "ROLE POST",
		},
		Mgr: PostMgr,
	},
}

type PostController struct {
	controller.JSONController
}
