// generated by xgen -- DO NOT EDIT
package internal

import (
	"bytes"

	"gopkg.in/goyy/goyy.v0/data/entity"
)

func NewRoleEntities(v int) *RoleEntities {
	entities := &RoleEntities{}
	entities.Make(v)
	return entities
}

type RoleEntities struct {
	datas []*Role
}

func (me *RoleEntities) Make(cap int) {
	me.datas = make([]*Role, 0, cap)
}

func (me *RoleEntities) New() entity.Interface {
	return NewRole()
}

func (me *RoleEntities) Append(v entity.Interface) {
	me.datas = append(me.datas, v.(*Role))
}

func (me *RoleEntities) Len() int {
	return len(me.datas)
}

func (me *RoleEntities) Cap() int {
	return cap(me.datas)
}

func (me *RoleEntities) Index(v int) entity.Interface {
	return me.datas[v]
}

func (me *RoleEntities) Slice() interface{} {
	return me.datas
}

func (me *RoleEntities) Value(v int) *Role {
	return me.datas[v]
}

func (me *RoleEntities) Values() []*Role {
	return me.datas
}

func (me *RoleEntities) JSON() string {
	var b bytes.Buffer
	b.WriteString(`{"datas":[`)
	for i := 0; i < me.Len(); i++ {
		if i > 0 {
			b.WriteString(",")
		}
		b.WriteString(me.Index(i).JSON())
	}
	b.WriteString("]}")
	return b.String()
}
