// generated by xgen -- DO NOT EDIT
package internal

import (
	"bytes"

	"gopkg.in/goyy/goyy.v0/data/entity"
)

func NewUserEntities(v int) *UserEntities {
	entities := &UserEntities{}
	entities.Make(v)
	return entities
}

type UserEntities struct {
	datas []*User
}

func (me *UserEntities) Make(cap int) {
	me.datas = make([]*User, 0, cap)
}

func (me *UserEntities) New() entity.Interface {
	return NewUser()
}

func (me *UserEntities) Append(v entity.Interface) {
	me.datas = append(me.datas, v.(*User))
}

func (me *UserEntities) Len() int {
	return len(me.datas)
}

func (me *UserEntities) Cap() int {
	return cap(me.datas)
}

func (me *UserEntities) Index(v int) entity.Interface {
	return me.datas[v]
}

func (me *UserEntities) Slice() interface{} {
	return me.datas
}

func (me *UserEntities) Value(v int) *User {
	return me.datas[v]
}

func (me *UserEntities) Values() []*User {
	return me.datas
}

func (me *UserEntities) JSON() string {
	var b bytes.Buffer
	b.WriteString(`{"datas":[`)
	for i := 0; i < me.Len(); i++ {
		if i > 0 {
			b.WriteString(",")
		}
		b.WriteString(me.Index(i).JSON())
	}
	b.WriteString("]}")
	return b.String()
}
