// generated by xgen -- DO NOT EDIT
package internal

import (
	"gopkg.in/goyy/goyy.v0/data/entity"
)

func NewPermissionEntities(v int) *PermissionEntities {
	entities := &PermissionEntities{}
	entities.Make(v)
	return entities
}

type PermissionEntities struct {
	datas []*Permission
}

func (me *PermissionEntities) Make(cap int) {
	me.datas = make([]*Permission, 0, cap)
}

func (me *PermissionEntities) New() entity.Interface {
	return NewPermission()
}

func (me *PermissionEntities) Append(v entity.Interface) {
	me.datas = append(me.datas, v.(*Permission))
}

func (me *PermissionEntities) Len() int {
	return len(me.datas)
}

func (me *PermissionEntities) Cap() int {
	return cap(me.datas)
}

func (me *PermissionEntities) Index(v int) entity.Interface {
	return me.datas[v]
}

func (me *PermissionEntities) Slice() interface{} {
	return me.datas
}

func (me *PermissionEntities) Value(v int) *Permission {
	return me.datas[v]
}

func (me *PermissionEntities) Values() []*Permission {
	return me.datas
}
