// generated by xgen -- DO NOT EDIT
package internal

import (
	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/service"
)

var UserMgr = &UserManager{
	Manager: service.Manager{
		Entity: func() entity.Interface {
			return NewUser()
		},
		Entities: func() entity.Interfaces {
			return NewUserEntities(10)
		},
	},
}

type UserManager struct {
	service.Manager
}
