// generated by xgen -- DO NOT EDIT
package internal

import (
	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/service"
)

var PermissionMgr = &PermissionManager{
	Manager: service.Manager{
		Entity: func() entity.Interface {
			return NewPermission()
		},
		Entities: func() entity.Interfaces {
			return NewPermissionEntities(10)
		},
	},
}

type PermissionManager struct {
	service.Manager
}
