// generated by xgen -- DO NOT EDIT
package product

import (
	"bytes"

	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/schema"
	"gopkg.in/goyy/goyy.v0/data/validate"
	"gopkg.in/goyy/goyy.v0/util/jsons"
	"gopkg.in/goyy/goyy.v0/util/strings"
)

var (
	ENTITY           = schema.TABLE("eg_product", "产品信息")
	ENTITY_ID        = ENTITY.PRIMARY("id", "标识")
	ENTITY_MEMO      = ENTITY.COLUMN("memo", "备注")
	ENTITY_CREATES   = ENTITY.COLUMN("creates", "创建机构")
	ENTITY_CREATER   = ENTITY.CREATER("creater", "创建人员")
	ENTITY_CREATED   = ENTITY.CREATED("created", "创建时间")
	ENTITY_MODIFIER  = ENTITY.MODIFIER("modifier", "更新人员")
	ENTITY_MODIFIED  = ENTITY.MODIFIED("modified", "更新时间")
	ENTITY_VERSION   = ENTITY.VERSION("version", "乐观锁")
	ENTITY_DELETION  = ENTITY.DELETION("deletion", "删除标志")
	ENTITY_ARTIFICAL = ENTITY.COLUMN("artifical", "人造数据")
	ENTITY_HISTORY   = ENTITY.COLUMN("history", "历史数据")
	ENTITY_NAME      = ENTITY.COLUMN("name", "名称")
	ENTITY_NUM       = ENTITY.COLUMN("num", "库存数")
	ENTITY_PRICE     = ENTITY.COLUMN("price", "价格")
)

func NewEntity() *Entity {
	e := &Entity{}
	e.init()
	return e
}

func (me *Entity) Name() string {
	return me.name.Value()
}

func (me *Entity) SetName(v string) {
	me.name.SetValue(v)
}

func (me *Entity) Num() int {
	return me.num.Value()
}

func (me *Entity) SetNum(v int) {
	me.num.SetValue(v)
}

func (me *Entity) Price() float64 {
	return me.price.Value()
}

func (me *Entity) SetPrice(v float64) {
	me.price.SetValue(v)
}

func (me *Entity) init() {
	me.table = ENTITY
	me.initSetDict()
	me.initSetColumn()
	me.initSetDefault()
	me.initSetField()
	me.initSetExcel()
	me.initSetJson()
	me.initSetXml()
}

func (me *Entity) initSetDict() {
}

func (me *Entity) initSetColumn() {
	if t, ok := me.Sys.Type("id"); ok {
		t.SetColumn(ENTITY_ID)
	}
	if t, ok := me.Sys.Type("memo"); ok {
		t.SetColumn(ENTITY_MEMO)
	}
	if t, ok := me.Sys.Type("creates"); ok {
		t.SetColumn(ENTITY_CREATES)
	}
	if t, ok := me.Sys.Type("creater"); ok {
		t.SetColumn(ENTITY_CREATER)
	}
	if t, ok := me.Sys.Type("created"); ok {
		t.SetColumn(ENTITY_CREATED)
	}
	if t, ok := me.Sys.Type("modifier"); ok {
		t.SetColumn(ENTITY_MODIFIER)
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetColumn(ENTITY_MODIFIED)
	}
	if t, ok := me.Sys.Type("version"); ok {
		t.SetColumn(ENTITY_VERSION)
	}
	if t, ok := me.Sys.Type("deletion"); ok {
		t.SetColumn(ENTITY_DELETION)
	}
	if t, ok := me.Sys.Type("artifical"); ok {
		t.SetColumn(ENTITY_ARTIFICAL)
	}
	if t, ok := me.Sys.Type("history"); ok {
		t.SetColumn(ENTITY_HISTORY)
	}
	me.name.SetColumn(ENTITY_NAME)
	me.num.SetColumn(ENTITY_NUM)
	me.price.SetColumn(ENTITY_PRICE)
}

func (me *Entity) initSetDefault() {
	if t, ok := me.Sys.Type("created"); ok {
		t.SetDefault("-62135596800")
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetDefault("-62135596800")
	}
}

func (me *Entity) initSetField() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.SetField(entity.DefaultField())
		}
	}
	me.name.SetField(entity.DefaultField())
	me.num.SetField(entity.DefaultField())
	me.price.SetField(entity.DefaultField())
}

func (me *Entity) initSetExcel() {
}

func (me *Entity) initSetJson() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.Field().SetJson(entity.NewJsonBy(c))
		}
	}
	me.name.Field().SetJson(entity.NewJsonBy("name"))
	me.num.Field().SetJson(entity.NewJsonBy("num"))
	me.price.Field().SetJson(entity.NewJsonBy("price"))
}

func (me *Entity) initSetXml() {
	for _, c := range entity.SysColumns {
		if t, ok := me.Sys.Type(c); ok {
			t.Field().SetXml(entity.NewXmlBy(c))
		}
	}
	me.name.Field().SetXml(entity.NewXmlBy("name"))
	me.num.Field().SetXml(entity.NewXmlBy("num"))
	me.price.Field().SetXml(entity.NewXmlBy("price"))
}

func (me Entity) New() entity.Interface {
	return NewEntity()
}

func (me *Entity) Get(column string) interface{} {
	switch column {
	case ENTITY_NAME.Name():
		return me.name.Value()
	case ENTITY_NUM.Name():
		return me.num.Value()
	case ENTITY_PRICE.Name():
		return me.price.Value()
	}
	return me.Sys.Get(column)
}

func (me *Entity) GetPtr(column string) interface{} {
	switch column {
	case ENTITY_NAME.Name():
		return me.name.ValuePtr()
	case ENTITY_NUM.Name():
		return me.num.ValuePtr()
	case ENTITY_PRICE.Name():
		return me.price.ValuePtr()
	}
	return me.Sys.GetPtr(column)
}

func (me *Entity) GetString(field string) string {
	switch strings.ToLowerFirst(field) {
	case "name":
		return me.name.String()
	case "num":
		return me.num.String()
	case "price":
		return me.price.String()
	}
	return me.Sys.GetString(field)
}

func (me *Entity) SetString(field, value string) error {
	switch strings.ToLowerFirst(field) {
	case "name":
		return me.name.SetString(value)
	case "num":
		return me.num.SetString(value)
	case "price":
		return me.price.SetString(value)
	}
	return me.Sys.SetString(field, value)
}

func (me *Entity) Table() schema.Table {
	return me.table
}

func (me *Entity) Type(column string) (entity.Type, bool) {
	switch column {
	case ENTITY_NAME.Name():
		return &me.name, true
	case ENTITY_NUM.Name():
		return &me.num, true
	case ENTITY_PRICE.Name():
		return &me.price, true
	}
	return me.Sys.Type(column)
}

func (me *Entity) Column(field string) (schema.Column, bool) {
	switch strings.ToLowerFirst(field) {
	case "name":
		return ENTITY_NAME, true
	case "num":
		return ENTITY_NUM, true
	case "price":
		return ENTITY_PRICE, true
	}
	return me.Sys.Column(field)
}

func (me *Entity) Columns() []schema.Column {
	return []schema.Column{
		ENTITY_ID,
		ENTITY_MEMO,
		ENTITY_CREATES,
		ENTITY_CREATER,
		ENTITY_CREATED,
		ENTITY_MODIFIER,
		ENTITY_MODIFIED,
		ENTITY_VERSION,
		ENTITY_DELETION,
		ENTITY_ARTIFICAL,
		ENTITY_HISTORY,
		ENTITY_NAME,
		ENTITY_NUM,
		ENTITY_PRICE,
	}
}

func (me *Entity) Names() []string {
	return []string{
		"id",
		"memo",
		"creates",
		"creater",
		"created",
		"modifier",
		"modified",
		"version",
		"deletion",
		"artifical",
		"history",
		"name",
		"num",
		"price",
	}
}

func (me *Entity) Value() *Entity {
	return me
}

func (me *Entity) Validate() error {
	validation := &validate.Validation{}
	if err := validation.Required("name", me.name.String()); err != nil {
		return err
	}
	if err := validation.Required("num", me.num.String()); err != nil {
		return err
	}
	if err := validation.Min("num", me.num.String(), 10); err != nil {
		return err
	}
	if err := validation.Required("price", me.price.String()); err != nil {
		return err
	}
	return nil
}

func (me *Entity) JSON() string {
	var b bytes.Buffer
	b.WriteString("{")
	b.WriteString(`"id":"` + jsons.Format(me.GetString("id")) + `"`)
	b.WriteString(`,"memo":"` + jsons.Format(me.GetString("memo")) + `"`)
	b.WriteString(`,"creates":"` + jsons.Format(me.GetString("creates")) + `"`)
	b.WriteString(`,"creater":"` + jsons.Format(me.GetString("creater")) + `"`)
	b.WriteString(`,"created":` + me.GetString("created"))
	b.WriteString(`,"modifier":"` + jsons.Format(me.GetString("modifier")) + `"`)
	b.WriteString(`,"modified":` + me.GetString("modified"))
	b.WriteString(`,"version":` + me.GetString("version"))
	b.WriteString(`,"deletion":` + me.GetString("deletion"))
	b.WriteString(`,"artifical":` + me.GetString("artifical"))
	b.WriteString(`,"history":` + me.GetString("history"))
	b.WriteString(`,"name":"` + jsons.Format(me.GetString("name")) + `"`)
	b.WriteString(`,"num":` + me.GetString("num"))
	b.WriteString(`,"price":` + me.GetString("price"))
	b.WriteString("}")
	return b.String()
}

func (me *Entity) ExcelColumns() []string {
	return nil
}
