// generated by xgen -- DO NOT EDIT
package conf

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type DTOs []DTO

type DTO struct {
	dto.Sys
	Name    string `json:"name"`
	Code    string `json:"code"`
	Content string `json:"content"`
	Genre   string `json:"genre"`
	Usable  string `json:"usable"`
	Ordinal string `json:"ordinal"`
}
