// generated by xgen -- DO NOT EDIT
package post

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var menuCtl = &MenuController{
	ClientController: controller.ClientController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "post.menu",
			Title:   "POST MENU",
		},
		DTO: func() interface{} {
			return &MenuDTO{}
		},
		DTOs: func() interface{} {
			return &MenuDTOs{}
		},
	},
}

type MenuController struct {
	controller.ClientController
}
