// generated by xgen -- DO NOT EDIT
package post

import (
	"gopkg.in/goyy/goyy.v0/data/dto"
)

type MenuDTOs []MenuDTO

type MenuDTO struct {
	dto.Sys
	PostId string `json:"postId"`
	MenuId string `json:"menuId"`
}
