// generated by xgen -- DO NOT EDIT
package dict

import (
	"bytes"
	"fmt"

	"gopkg.in/goyy/goyy.v0/data/entity"
	"gopkg.in/goyy/goyy.v0/data/schema"
	"gopkg.in/goyy/goyy.v0/util/strings"
)

var (
	ENTITY           = schema.TABLE("sys_dict", "DICT")
	ENTITY_ID        = ENTITY.PRIMARY("id", "ID")
	ENTITY_MEMO      = ENTITY.COLUMN("memo", "MEMO")
	ENTITY_CREATES   = ENTITY.COLUMN("creates", "CREATES")
	ENTITY_CREATER   = ENTITY.CREATER("creater", "CREATER")
	ENTITY_CREATED   = ENTITY.CREATED("created", "CREATED")
	ENTITY_MODIFIER  = ENTITY.MODIFIER("modifier", "MODIFIER")
	ENTITY_MODIFIED  = ENTITY.MODIFIED("modified", "MODIFIED")
	ENTITY_VERSION   = ENTITY.VERSION("version", "VERSION")
	ENTITY_DELETION  = ENTITY.DELETION("deletion", "DELETION")
	ENTITY_ARTIFICAL = ENTITY.COLUMN("artifical", "ARTIFICAL")
	ENTITY_HISTORY   = ENTITY.COLUMN("history", "HISTORY")
	ENTITY_GENRE     = ENTITY.COLUMN("genre", "GENRE")
	ENTITY_DESCR     = ENTITY.COLUMN("descr", "DESCR")
	ENTITY_MKEY      = ENTITY.COLUMN("mkey", "MKEY")
	ENTITY_MVAL      = ENTITY.COLUMN("mval", "MVAL")
	ENTITY_FILTERS   = ENTITY.COLUMN("filters", "FILTERS")
	ENTITY_ORDINAL   = ENTITY.COLUMN("ordinal", "ORDINAL")
)

func NewEntity() *Entity {
	e := &Entity{}
	e.init()
	return e
}

func (me *Entity) Genre() string {
	return me.genre.Value()
}

func (me *Entity) SetGenre(v string) {
	me.genre.SetValue(v)
}

func (me *Entity) Descr() string {
	return me.descr.Value()
}

func (me *Entity) SetDescr(v string) {
	me.descr.SetValue(v)
}

func (me *Entity) Mkey() string {
	return me.mkey.Value()
}

func (me *Entity) SetMkey(v string) {
	me.mkey.SetValue(v)
}

func (me *Entity) Mval() string {
	return me.mval.Value()
}

func (me *Entity) SetMval(v string) {
	me.mval.SetValue(v)
}

func (me *Entity) Filters() string {
	return me.filters.Value()
}

func (me *Entity) SetFilters(v string) {
	me.filters.SetValue(v)
}

func (me *Entity) Ordinal() string {
	return me.ordinal.Value()
}

func (me *Entity) SetOrdinal(v string) {
	me.ordinal.SetValue(v)
}

func (me *Entity) init() {
	me.table = ENTITY

	if t, ok := me.Sys.Type("id"); ok {
		t.SetColumn(ENTITY_ID)
	}
	if t, ok := me.Sys.Type("memo"); ok {
		t.SetColumn(ENTITY_MEMO)
	}
	if t, ok := me.Sys.Type("creates"); ok {
		t.SetColumn(ENTITY_CREATES)
	}
	if t, ok := me.Sys.Type("creater"); ok {
		t.SetColumn(ENTITY_CREATER)
	}
	if t, ok := me.Sys.Type("created"); ok {
		t.SetColumn(ENTITY_CREATED)
	}
	if t, ok := me.Sys.Type("modifier"); ok {
		t.SetColumn(ENTITY_MODIFIER)
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetColumn(ENTITY_MODIFIED)
	}
	if t, ok := me.Sys.Type("version"); ok {
		t.SetColumn(ENTITY_VERSION)
	}
	if t, ok := me.Sys.Type("deletion"); ok {
		t.SetColumn(ENTITY_DELETION)
	}
	if t, ok := me.Sys.Type("artifical"); ok {
		t.SetColumn(ENTITY_ARTIFICAL)
	}
	if t, ok := me.Sys.Type("history"); ok {
		t.SetColumn(ENTITY_HISTORY)
	}
	me.genre.SetColumn(ENTITY_GENRE)
	me.descr.SetColumn(ENTITY_DESCR)
	me.mkey.SetColumn(ENTITY_MKEY)
	me.mval.SetColumn(ENTITY_MVAL)
	me.filters.SetColumn(ENTITY_FILTERS)
	me.ordinal.SetColumn(ENTITY_ORDINAL)

	if t, ok := me.Sys.Type("created"); ok {
		t.SetDefault("-62135596800")
	}
	if t, ok := me.Sys.Type("modified"); ok {
		t.SetDefault("-62135596800")
	}

	columns := []string{"id", "memo", "creates", "creater", "created", "modifier", "modified",
		"version", "deletion", "artifical", "history"}
	for _, c := range columns {
		if t, ok := me.Sys.Type(c); ok {
			t.SetField(entity.DefaultField())
		}
	}
	me.genre.SetField(entity.DefaultField())
	me.descr.SetField(entity.DefaultField())
	me.mkey.SetField(entity.DefaultField())
	me.mval.SetField(entity.DefaultField())
	me.filters.SetField(entity.DefaultField())
	me.ordinal.SetField(entity.DefaultField())
}

func (me Entity) New() entity.Interface {
	return NewEntity()
}

func (me *Entity) Get(column string) interface{} {
	switch column {
	case ENTITY_GENRE.Name():
		return me.genre.Value()
	case ENTITY_DESCR.Name():
		return me.descr.Value()
	case ENTITY_MKEY.Name():
		return me.mkey.Value()
	case ENTITY_MVAL.Name():
		return me.mval.Value()
	case ENTITY_FILTERS.Name():
		return me.filters.Value()
	case ENTITY_ORDINAL.Name():
		return me.ordinal.Value()
	}
	return me.Sys.Get(column)
}

func (me *Entity) GetPtr(column string) interface{} {
	switch column {
	case ENTITY_GENRE.Name():
		return me.genre.ValuePtr()
	case ENTITY_DESCR.Name():
		return me.descr.ValuePtr()
	case ENTITY_MKEY.Name():
		return me.mkey.ValuePtr()
	case ENTITY_MVAL.Name():
		return me.mval.ValuePtr()
	case ENTITY_FILTERS.Name():
		return me.filters.ValuePtr()
	case ENTITY_ORDINAL.Name():
		return me.ordinal.ValuePtr()
	}
	return me.Sys.GetPtr(column)
}

func (me *Entity) Table() schema.Table {
	return me.table
}

func (me *Entity) Type(column string) (entity.Type, bool) {
	switch column {
	case ENTITY_GENRE.Name():
		return &me.genre, true
	case ENTITY_DESCR.Name():
		return &me.descr, true
	case ENTITY_MKEY.Name():
		return &me.mkey, true
	case ENTITY_MVAL.Name():
		return &me.mval, true
	case ENTITY_FILTERS.Name():
		return &me.filters, true
	case ENTITY_ORDINAL.Name():
		return &me.ordinal, true
	}
	return me.Sys.Type(column)
}

func (me *Entity) Column(field string) (schema.Column, bool) {
	switch strings.ToLowerFirst(field) {
	case "genre":
		return ENTITY_GENRE, true
	case "descr":
		return ENTITY_DESCR, true
	case "mkey":
		return ENTITY_MKEY, true
	case "mval":
		return ENTITY_MVAL, true
	case "filters":
		return ENTITY_FILTERS, true
	case "ordinal":
		return ENTITY_ORDINAL, true
	}
	return me.Sys.Column(field)
}

func (me *Entity) Columns() []schema.Column {
	return []schema.Column{
		ENTITY_ID,
		ENTITY_MEMO,
		ENTITY_CREATES,
		ENTITY_CREATER,
		ENTITY_CREATED,
		ENTITY_MODIFIER,
		ENTITY_MODIFIED,
		ENTITY_VERSION,
		ENTITY_DELETION,
		ENTITY_ARTIFICAL,
		ENTITY_HISTORY,
		ENTITY_GENRE,
		ENTITY_DESCR,
		ENTITY_MKEY,
		ENTITY_MVAL,
		ENTITY_FILTERS,
		ENTITY_ORDINAL,
	}
}

func (me *Entity) Names() []string {
	return []string{
		"id",
		"memo",
		"creates",
		"creater",
		"created",
		"modifier",
		"modified",
		"version",
		"deletion",
		"artifical",
		"history",
		"genre",
		"descr",
		"mkey",
		"mval",
		"filters",
		"ordinal",
	}
}

func (me *Entity) Value() *Entity {
	return me
}

func (me *Entity) SetString(field, value string) error {
	switch strings.ToLowerFirst(field) {
	case "genre":
		return me.genre.SetString(value)
	case "descr":
		return me.descr.SetString(value)
	case "mkey":
		return me.mkey.SetString(value)
	case "mval":
		return me.mval.SetString(value)
	case "filters":
		return me.filters.SetString(value)
	case "ordinal":
		return me.ordinal.SetString(value)
	}
	return me.Sys.SetString(field, value)
}

func (me *Entity) Validate() error {
	return nil
}

func (me *Entity) JSON() string {
	var b bytes.Buffer
	b.WriteString("{")
	b.WriteString(fmt.Sprintf(`"id":%q`, me.Sys.Pk.Id()))
	b.WriteString(fmt.Sprintf(`,"memo":%q`, me.Sys.Memo()))
	b.WriteString(fmt.Sprintf(`,"creates":%q`, me.Sys.Creates()))
	b.WriteString(fmt.Sprintf(`,"creater":%q`, me.Sys.Creater()))
	b.WriteString(fmt.Sprintf(`,"created":%d`, me.Sys.Created()))
	b.WriteString(fmt.Sprintf(`,"modifier":%q`, me.Sys.Modifier()))
	b.WriteString(fmt.Sprintf(`,"modified":%d`, me.Sys.Modified()))
	b.WriteString(fmt.Sprintf(`,"version":%d`, me.Sys.Version()))
	b.WriteString(fmt.Sprintf(`,"deletion":%d`, me.Sys.Deletion()))
	b.WriteString(fmt.Sprintf(`,"artifical":%d`, me.Sys.Artifical()))
	b.WriteString(fmt.Sprintf(`,"history":%d`, me.Sys.History()))
	b.WriteString(fmt.Sprintf(`,"genre":%q`, me.genre.String()))
	b.WriteString(fmt.Sprintf(`,"descr":%q`, me.descr.String()))
	b.WriteString(fmt.Sprintf(`,"mkey":%q`, me.mkey.String()))
	b.WriteString(fmt.Sprintf(`,"mval":%q`, me.mval.String()))
	b.WriteString(fmt.Sprintf(`,"filters":%q`, me.filters.String()))
	b.WriteString(fmt.Sprintf(`,"ordinal":%q`, me.ordinal.String()))
	b.WriteString("}")
	return b.String()
}
