// generated by xgen -- DO NOT EDIT
package dict

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var ctl = &Controller{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "dict",
			Title:   "DICT",
		},
		Mgr: Mgr,
	},
}

type Controller struct {
	controller.JSONController
}
